id: I4E446D64
legacy_id: P000360
ocr_import_info:
  bdrc_scan_id: W30536
  source: bdrc
  ocr_info:
    timestamp: '2020-03-16T11:17:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T12:03:46.841798+00:00'
last_modified: 2022-09-03 20:04:19.206334
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30536
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW30536
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔྱད་གསུམ་དག་རྩིས་བསྐལ་སྲིད་དུས་འཁོར།
  author: ཁྱུང་སྤྲུལ་འཇིགས་མེད་ནམ་མཁའི་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.5095934881314297
  ocr_word_median_confidence_index: 0.44999998807907104
quality: null
bases:
  I6453:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6453
      total_pages: 742
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I6453.txt
    statistics:
      ocr_word_median_confidence_index: 0.4399999976158142
      ocr_word_mean_confidence_index: 0.5255841149076051
    legacy_id: v002
  I6452:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6452
      total_pages: 784
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6452.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.49809847401214324
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
